# Generated by Django 5.2.1 on 2025-06-02 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD к RUB')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время получения курса')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
